Create link feature
MetaCell/PsyNeuLinkView pull request #118
Opened 2023-06-25 15:04 UTC by emekauja

create project from any mechanism views

2023-06-27 17:41 UTC, afonsobspinto requested changes
Looks good, just contains a small typo.

I assume the link not starting in the right place is to be address by other issue correct? cc @ddelpiano

2023-06-27 17:41 UTC, afonsobspinto commented on src/client/components/views/editView/MainEdit.js
> +      <div className={classes.root} onMouseMove={this.mouseMoveCallback} onMo>
onMo seems a typo

2023-06-27 17:41 UTC, afonsobspinto commented on src/client/components/views/editView/mechanisms/shared/PortsList.js
> +        <Snackbar
nice :+1:

2023-06-28 20:25 UTC, ddelpiano approved these changes

2023-06-28 20:25 UTC, merged