feature: create projection not connected to model
MetaCell/PsyNeuLinkView pull request #124
Opened 2023-07-10 09:20 UTC by emekauja

Projections instantiated from the sidebar are not connected to the metaGraph model

2023-07-12 14:12 UTC, emekauja commented
PSYNEU-89: added  Use a single projection component, which is part of this [PR]

2023-07-17 00:54 UTC, ddelpiano submitted a review, later dismissed

2023-07-17 00:57 UTC, ddelpiano commented
lgtm, @afonsobspinto could you please have a look to this as well? Thx

2023-07-17 13:11 UTC, afonsobspinto requested changes

2023-07-17 13:11 UTC, afonsobspinto commented on src/client/model/state/CreateLinkState.ts
> +            this.link = this.engine.getModel().addLink(link) as MetaLinkModel;
This is a detail, but I would like to see using the same naming convention that we do [here](https://github.com/MetaCell/PsyNeuLinkView/blob/feature/PSYNEU_91/src/client/model/links/ProjectionLink.ts#L27). Maybe we can refactor a method (generate link name) that we can use in both places

2023-07-17 13:11 UTC, afonsobspinto commented on src/client/model/state/CreateLinkState.ts
>            if (element instanceof MetaNodeModel) {
I think this check is too broad. We shouldn't allow projections on compositions.
But the app shouldn't crash because of that

https://github.com/MetaCell/PsyNeuLinkView/assets/19196034/cabb491d-4884-4fb9-859f-65ae0c525346

2023-07-17 16:45 UTC, emekauja commented on src/client/model/state/CreateLinkState.ts
> +            this.link = this.engine.getModel().addLink(link) as MetaLinkModel;
this takes more time than expected , left out

2023-07-17 17:01 UTC, afonsobspinto approved these changes

2023-07-17 17:34 UTC, merged