#PSYNEU-137 - Install rosetta as part of pip installation process
MetaCell/PsyNeuLinkView pull request #156
Opened 2024-07-26 07:39 UTC by jrmartin

Ask first if the user wants to, otherwise print an error as it’s a required dependency.

If yes, trigger the rosetta installation.

The pip installer should wait for the installation to be completed (single thread or put a condition for the rosetta files to be present in the system before to move forward).

2024-07-28 15:42 UTC, ddelpiano requested changes
same recommendation give for the other 2 prs, we need to wrap the subprocess check to handle exceptions, the rest looks good, good job 👍🏽

2024-08-06 09:56 UTC, ddelpiano requested changes

2024-08-06 09:56 UTC, ddelpiano commented on package/psyneulinkviewer/rosetta.py
> +            rosetta_version = subprocess.run(
same here https://github.com/MetaCell/PsyNeuLinkView/pull/155#discussion_r1705255716

2024-08-06 12:31 UTC, jrmartin commented on package/psyneulinkviewer/rosetta.py
> +            rosetta_version = subprocess.run(
Fixed

2024-08-09 14:26 UTC, merged