Feature/45 Right Sidebar Frontend implementation
MetaCell/PsyNeuLinkView pull request #57
Opened 2022-10-20 00:44 UTC by emekauja

![Uploading Screenshot 2022-10-20 at 1.28.12 AM.png…]()

2022-10-26 12:07 UTC, vidhya-metacell commented on src/components/Main.js
> +    margin: 'none',
@emekauja margin and padding values are not working, also i don't see the value add even id they were.

2022-10-26 12:10 UTC, vidhya-metacell commented on src/components/views/Sidebar/Sidebar.js
> +            <Typography component="body2" fontWeight={500}>
@emekauja body2 is a variant, not a component, hence no properties of body2 are reflecting

2022-10-26 12:13 UTC, vidhya-metacell commented on src/components/views/Sidebar/Sidebar.js
> +          <Box paddingLeft="1.5rem" paddingY={1.5}>
@emekauja Incorrect padding should be an px passing instead of just left. Left would 2 not 1.5, so px={2}

2022-10-26 12:47 UTC, vidhya-metacell commented
Hi @emekauja , i reviewed the UI of the sidebar, found the following issues:
<img width="276" alt="Screen Shot 2022-10-26 at 2 04 06 PM" src="https://user-images.githubusercontent.com/71261494/198021510-31c932d7-dad0-4a07-972d-61b2af56e52d.png">

- The width is not like figma, border and border color do not match to figma and there is no box shadow in figma
<img width="141" alt="Screen Shot 2022-10-26 at 2 13 49 PM" src="https://user-images.githubusercontent.com/71261494/198023316-1508ac52-53d5-44b2-86c3-65842cfd9c2c.png">

- The arrow icon is different in figma.
<img width="55" alt="Screen Shot 2022-10-26 at 2 17 13 PM" src="https://user-images.githubusercontent.com/71261494/198023967-649c4d8d-099e-47e6-8e73-782617f7c09a.png">
- There is no space/padding on the left of the arrow icon in figma
<img width="285" alt="Screen Shot 2022-10-26 at 2 30 02 PM" src="https://user-images.githubusercontent.com/71261494/198026441-ed39bf24-2aa5-4937-87d2-a60017ca9c37.png">

- Once i expand this composition, i can never collapse it. always remains expanded.

<img width="298" alt="Screen Shot 2022-10-26 at 2 32 59 PM" src="https://user-images.githubusercontent.com/71261494/198026944-9047ba28-03b4-4100-89fb-396a035cfde7.png">

- The child icon should be vertically aligned with the Composition text


<img width="311" alt="Screen Shot 2022-10-26 at 2 37 56 PM" src="https://user-images.githubusercontent.com/71261494/198027947-43e66687-e192-4bed-b58e-d6f6f8f71532.png">

- The arrow icon of the child B2 should be aligned with Projection A2 icon

<img width="57" alt="Screen Shot 2022-10-26 at 2 44 50 PM" src="https://user-images.githubusercontent.com/71261494/198029310-ebba5661-1ab2-46de-8455-67c5c5c04da2.png">

- These two icons, do not have as much spacing between each other, please refer to figma again. I see extra padding left and margin-right adding this space. Overall spacing between these elements should be considered again using figma.

2022-10-26 13:10 UTC, vidhya-metacell commented
@emekauja found the following issues with font properties

1. The overall letter spacing should be as in figma

<img width="274" alt="Screen Shot 2022-10-26 at 2 51 45 PM" src="https://user-images.githubusercontent.com/71261494/198030639-007d14e9-91ff-4f58-91dc-4fba26db241f.png">

- The height of the row is 36 not 42. Please keep an eye on the details.

<img width="221" alt="Screen Shot 2022-10-26 at 2 53 04 PM" src="https://user-images.githubusercontent.com/71261494/198030973-332ffed9-2baa-4c8b-8c22-d832d6c8df76.png">

- On hover the background color changes to white, it should remain the same.


<img width="250" alt="Screen Shot 2022-10-26 at 2 56 29 PM" src="https://user-images.githubusercontent.com/71261494/198031597-b5a42f5c-a138-49dc-ad30-48a26c340813.png">
- The font weight of the composition heading should be 500, in figma is see 510, please use 500 instead of 600.
- remove letter spacing its not there in figma

- 
<img width="680" alt="Screen Shot 2022-10-26 at 2 59 02 PM" src="https://user-images.githubusercontent.com/71261494/198032112-3c1b7637-ebd8-4696-ab5f-a59a2955d94b.png">

-  use font weight same as composition heading for the labels, 500
- fix the line height
- remove letter spacing, keep it normal
<img width="567" alt="Screen Shot 2022-10-26 at 3 00 51 PM" src="https://user-images.githubusercontent.com/71261494/198032507-e569f2ba-59d9-4181-8f62-b41aa01d6d01.png">

- Label is missing this 2px margin
<img width="560" alt="Screen Shot 2022-10-26 at 3 02 14 PM" src="https://user-images.githubusercontent.com/71261494/198032775-5928e549-fca4-4dee-934b-858f0a7b549d.png">

- Values for the line height, letter spacing, font size , font color, are not matching figma

<img width="549" alt="Screen Shot 2022-10-26 at 3 05 21 PM" src="https://user-images.githubusercontent.com/71261494/198033410-08b433f1-392a-463c-8e9d-7760067d55c4.png">

- From the box, flex, flex direction, align-items can be removed, not adding anything. Text overflow ellipsis should be removed, will not work on box. Ellipses should be on p tag

2022-11-01 10:19 UTC, ddelpiano requested changes
There is another problem noticed testing the sidebar.

If I click on the first composition and then try to compress this, the compression does not work unless I play with another item of the sidebar (deadlock in the state?), please fix this.

https://user-images.githubusercontent.com/37704177/199211871-a87e66f6-3dcd-4f03-8bdc-2c8d7e1a8b88.mp4

Other than this there are the changes requested by Vidhya and then this can be approved.

Thanks!

2022-11-01 10:19 UTC, ddelpiano commented on src/components/views/Sidebar/TreeView/InstanceTreeView.js
> +    // if (nodes.length !== nodeIds.length && nodes[0] === nodeIds[0]) {
@emekauja please remove commented code if not used

2022-11-08 16:54 UTC, ddelpiano approved these changes

2022-11-08 16:54 UTC, merged