#46 added  sidebar nodes
MetaCell/PsyNeuLinkView pull request #58
Opened 2022-11-02 14:06 UTC by emekauja

added sidebar nodes for the icons and label

2022-11-02 14:33 UTC, emekauja commented
<img width="583" alt="Screenshot 2022-11-02 at 3 28 08 PM" src="https://user-images.githubusercontent.com/60346432/199516830-da8a507d-9b5c-414f-8ce3-647cc6cfca38.png">

2022-11-03 14:56 UTC, ddelpiano requested changes
@emekauja just a minor typo and then this can be approved and merged. Thx

2022-11-03 14:56 UTC, ddelpiano commented on src/components/views/sidebar/nodes.js
> +    id: 'targetMechanism',
typo

2022-11-03 15:10 UTC, emekauja commented on src/components/views/sidebar/nodes.js
> +    id: 'targetMechanism',
fixed

2022-11-07 11:09 UTC, ddelpiano approved these changes

2022-11-07 19:15 UTC, ddelpiano approved these changes

2022-11-07 19:15 UTC, merged