Feature/flex layout
MetaCell/PsyNeuLinkView pull request #72
Opened 2023-01-20 10:18 UTC by emekauja

Customize flex-layout for psyneulink
<img width="1468" alt="Screenshot 2023-01-19 at 3 19 15 AM" src="https://user-images.githubusercontent.com/60346432/213671604-ed6d8492-2fa3-4234-afb4-ffbd0e9e7826.png">

2023-01-25 14:55 UTC, ddelpiano requested changes

2023-01-25 14:55 UTC, ddelpiano commented on installation.sh
> +		cd ../geppetto-meta/geppetto.js/geppetto-client/;
it does not seem we need only geppetto client but it seems that also geppetto-ui is used.
Also, what if I want to use a published version of geppetto meta? 
Could this be implemented as an additional option in the script?
Meta-diagram will follow the same pattern but for now hasn't been published yet.

2023-01-25 14:55 UTC, ddelpiano commented on installation.sh
> +	mv temp_env .env
why repeating this here and at the bottom?

2023-01-25 14:55 UTC, ddelpiano commented on installation.sh
> +	sed '/FAST_REFRESH/d' .env > temp_env
why repeating this and at the top?

2023-01-25 14:55 UTC, ddelpiano commented on package.json
> +    "@metacell/geppetto-meta-client": "file:.yalc/@metacell/geppetto-meta-client",
it would be ideal to have a dev-package.json so that we swap them during the installation if we want to use geppetto-meta from sources.

2023-01-25 14:55 UTC, ddelpiano commented on package.json
> +    "file-saver": "^2.0.5",
move to dev dependency

2023-01-25 14:55 UTC, ddelpiano commented on src/App.js
> +    <DndProvider backend={HTML5Backend}>
pretty sure we don't need this here but we can move it to wrap only the visualise layout.

2023-01-25 14:55 UTC, ddelpiano commented on src/components/common/Layout.js
> +          <Header />
ReactDnd could be placed here to wrap header and MainVisualise

2023-01-25 14:55 UTC, ddelpiano commented on src/components/views/visualiseView/Layout.js
> +export default VisualizeLayout;
Change file name please, call this Visualise Layout so we avoid confusion since there is already a layout.js component/file. Thx

2023-01-25 14:55 UTC, ddelpiano commented on src/components/views/visualiseView/Visualize.js
> +export default MainVisualize;
Why rename this? if needed could we please rename the component as well so we keep consistency whenever possible? Thx

2023-01-25 16:50 UTC, emekauja commented on installation.sh
> +	sed '/FAST_REFRESH/d' .env > temp_env
one is for installation `if [ "$INSTALL" = true ]; then`,
 and the other during update `elif [ "$UPDATE" = true ]; then
`

2023-01-27 11:56 UTC, ddelpiano commented on installation.sh
> +	sed '/FAST_REFRESH/d' .env > temp_env
you were repeating the editing of the .env file twice, I removed that

2023-01-27 12:04 UTC, ddelpiano requested changes

2023-01-27 12:04 UTC, ddelpiano commented on src/components/views/visualiseView/Visualize.js
> +  const classes = useStyles();
is this required? I don't see the classes used anywhere. Also the styling above, is that required? Thx

2023-01-27 14:40 UTC, merged